// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkizauftovexsnwyrkhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhraXphdWZ0b3ZleHNud3lya2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU2NTc1MjgsImV4cCI6MjA0MTIzMzUyOH0.V2JLuIze9i51DdBIPxPAA1HPGbRJpbn_SahtWmz1sps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);